name: container
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */5 * *' # run every 5 days

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: build-container
  cancel-in-progress: true

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - id: get-dockerfile-info
        name: get version from dockerfile
        run: |
          IMAGE=$(sed -nr 's/FROM (.*):(.*)/\1/p' Dockerfile)
          echo "image=$IMAGE"
          echo "::set-output name=image::$IMAGE"
          VERSION=$(sed -nr 's/FROM (.*):(.*)/\2/p' Dockerfile)
          echo "version=$VERSION"
          echo "::set-output name=version::$VERSION"
        shell: bash
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get-dockerfile-info.outputs.version }}
          labels: |
            org.opencontainers.image.version=${{ steps.get-dockerfile-info.outputs.version }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.title=argocd-git-crypt
            org.opencontainers.image.description=ArgoCD with automatic git-crypt decryption
            org.opencontainers.image.base.name=quay.io/argoproj/argocd
